### ISSUE TITLE
403 - Terraform

### ISSUE THREAD

**Issue by ramimmadi** [andreyk-code/no-inet-gke-cluster#1]
Hi I am trying to create a private dns zone in GCP using terraform But I am getting 403 error, whereas I am able to create the same with cloud commands. 

`resource "google_dns_managed_zone" "google-apis" {
  name        = local.google_apis_zone
  project     = ""
  dns_name    = local.dns_name
  description = "private zone for Google API's"

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = "https://www.googleapis.com/compute/v1/projects/local.project/global/networks/local.network"
    }
  }
}

`Error: Error creating ManagedZone: googleapi: Error 403: Forbidden, forbidden
  on dns.tf line 11, in resource "google_dns_managed_zone" "google-apis":
  11: resource "google_dns_managed_zone" "google-apis`

**Comment by andreyk-code** [comment]
Hello! 

It looks like the "network_url" value may need to be changed. In your example, the url has "local.project" and "local.network" in string format since they are within the quotes. Maybe try this instead:

```
network_url = "https://www.googleapis.com/compute/v1/projects/${local.project}/global/networks/${local.network}"
```

**Comment by ramimmadi** [comment]
Hi Andrey,

Thanks for the response.

It worked, the problem was with some additional brace. Not sure Why I got the 403 instead of syntax. However I am unable to pull Aston images from docker hub. These are not in mirror as well. Is there a way that I can allow specific docker images and block rest!!.. your inputs would be really helpful.

**Comment by andreyk-code** [comment]
Are you still having this issue?

**Comment by ramimmadi** [comment]
Hi,

Thanks for your reply. My issue got resolved.

But I had a different query , if we are removing the route to internet what
is the need to block firewalls... And if are using  cname , why do we need
A record?

Is there any specific reason for this? your response is highly appreciated.

Regards
Ram

**Comment by andreyk-code** [comment]
Great to hear!

The firewall block is to ensure that no egress traffic is allowed unless it's explicitly permitted. Helps overcome someone accidentally opening route to internet. 

CNAME is required for the instances in GCP to know they have to point to restricted.googleapis.com for any requests to *.googleapis.com. Without the CNAME, the instances will resolve to *.googleapis.com which would point to a public IP address.
